"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const product_controllers_1 = require("../controllers/product.controllers");
const auth_middleware_1 = require("../middleware/auth.middleware");
const role_middleware_1 = require("../middleware/role.middleware");
const router = (0, express_1.Router)();
router.get("/", product_controllers_1.getAll);
router.get("/:id", product_controllers_1.getOne);
router.post("/", auth_middleware_1.authMiddleware, (0, role_middleware_1.authorizeRoles)("admin"), product_controllers_1.create);
router.put("/:id", auth_middleware_1.authMiddleware, (0, role_middleware_1.authorizeRoles)("admin"), product_controllers_1.update);
router.delete("/:id", auth_middleware_1.authMiddleware, (0, role_middleware_1.authorizeRoles)("admin"), product_controllers_1.remove);
exports.default = router;
